apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: skaffold-deploy-profiles
profiles:
  - name: dev
    deploy:
      kubectl:
        manifests:
        - helm/templates/cart-deployment.yaml
        flags:
          global:
          - --namespace=robot-shop-dev

  - name: prod
    deploy:
      kubectl:
        manifests:
        - helm/templates/cart-deployment.yaml
        flags:
          global:
          - --namespace=robot-shop-prod
 








# build:
#     artifacts:
#       - image: us-central1-docker.pkg.dev/triangulum-ctv-349103/telus-robot-shop
# deploy:
#   helm:
#     releases:
#     - name: dev
#       chartPath: helm
#       namespace: robot-shop-dev
#       recreatePods: false
#       valuesFiles:
#         - helm/values.yaml
#       imageStrategy:
#         helm: {}
#     - name: prod
#       chartPath: helm
#       namespace: robot-shop-prod
#       recreatePods: false
#       valuesFiles:
#         - helm/values.yaml
#       imageStrategy:
#         helm: {}
  