name: test-k6-execution
on:
   push:
     branches-ignore:
       - main
env:
  GAR_INFO: us-central1-docker.pkg.dev/triangulum-ctv-349103/telus-robot-shop

jobs:
  run-performance-tests:
    name: Run Performace Tests using K6
   
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
                        
      - name: Setup GCP Service Account
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS_P }}"
      
      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: set K6 image TAG
        run: |
          K6_TAG=`cat qa-tests/VERSION.txt`
          echo "K6_TAG=$K6_TAG" >> $GITHUB_ENV

      - name: Build-K6-push-to-GAR
        run: |
          echo $K6_TAG
          echo "$GAR_INFO"/rs-k6-image:"$K6_TAG"
          docker build -t "$GAR_INFO"/rs-k6-image:"$K6_TAG" qa-tests/
          gcloud info
          docker push "$GAR_INFO"/rs-k6-image:"$K6_TAG"

      - name: Deploy Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          service: 'k6-test'
          image: '$GAR_INFO/rs-k6-image:K6_TAG'

  